SELECT EMP_NAME.SALARY
FROM EMPLOYEE
WHERE SALARY <= 3000000;

SELECT EMP_NAME,JOB_CODE
FROM EMPLOYEE
WHERE JOB_CODE! = 'J3';

SELECT EMP_NAME,BONUS
FROM EMPLOYEE
WHERE MANAGER_ID!=200;
--숫자의 경우 '' 사용하지 않아도 사용이 가능

SELECT EMP_NAME,EMAIL
FROM EMPLOYEE
WHERE EMAIL IS NULL;

--32. PHONE이 없는 사원의 이름과 전화번호
SELECT EMP_NAME,PHONE
FROM EMPLOYEE
WHERE PHONE IS NULL;

--33. BONUS가 없는 사원의 이름과 보너스
SELECT EMP_NAME,BONUS
FROM EMPLOYEE
WHERE BONUS IS NULL;

--34. MANAGER_ID가 없는 사원의 이름과 매니저 ID
SELECT EMP_NAME,MANAGER_ID
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

--35. ENT_DATE가 없는 사원의 이름과 종료일
SELECT EMP_NAME,ENT_DATE
FROM EMPLOYEE
WHERE ENT_DATS IS NULL;

/***** NULL 비교하기 IS NOT NULL *****/
SELECT EMP_NAME,EMAIL
FROM EMPLOYEE
WHERE EMAIL IS NOT NULL;
-->이메일칸에 이메일이 모두 작성된 사람들만 조회

--37.PHONE이 있는 사원의 이름과 전화번호
SELECT EMP_NAME,PHONE
FROM EMPLOYEE
WHERE PHONE IS NOT NULL;
--38.BONUS가 있는 사원의 이름과 전화번호

--39.
SELECT EMP_NAME,MANAGER_ID
FROM EMPLOYEE
WHERE manager_id IS NOT NULL;
--40.ENT_DATE가 있는 사원의 이름과 종료일
SELECT EMP_NAME,ENT_DATE
FROM EMPLOYEE
WHERE ENT_DATE IS NOT NULL;
/***** BETWEEN 연산자 사용 *****/
--41.SALARY가 2000000에서 3000000사이인 사원의 이름과 급여
SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 3000000;
--42. HIRE DATE가 2000년 1월1일부터 2010년 12월 31일 사이인 사원의 이름과 입사일
SELECT EMP_NAME,HIRE DATE
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD')
AND TO DATE('2010-12-31','YYYY-MM-DD');

SELECT EMP_NAME,EMP_ID
FROM EMPLOYEE
WHERE EMP_ID BETWEEN 210 AND 220;

SELECT EMP_NAME,BONUS
FROM EMPLOYEE
WHERE BONUS BETWEEN 0.1 AND 0.3;

SELECT EMP_NAME,SAL_LEVEL
FROM EMPLOYEE
WHERE SAL_LEVEL BETWEEN 'S3' AND 'S5';

/***** NOT BETWEEN 연산자 사용 *****/
--
SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE SALARY NOT BETWEEN 2000000 AND 3000000;

SELECT EMP_NAME, HIRE DATE
FROM EMPLOYEE
WHERE HIRE_DATE NOT BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD')
AND TO DATE('2010-12-31','YYYY-MM-DD');

SELECT EMP_NAME,EMP_ID
FROM EMPLOYEE
WHERE EMP_ID NOT BETWEEN 210 AND 220;

SELECT EMP_NAME,BONUS
FROM EMPLOYEE
WHERE BONUS NOT BETWEEN 0.1 AND 0.3;

SELECT EMP_NAME,SLA_LEVEL
FROM EMPLOYEE
WHERE SAL_LEVEL NOT BETWEEN 'S3'AND'S5';